export interface CrossFitBox {
  id: string
  name: string
  city: string
  district: string
  address: string
  dropinFee: string   // 확인된 경우만 기재, 불명확 시 '문의'
  phone: string       // 확인된 경우만 기재, 불명확 시 '문의'
  website?: string    // 확인된 공식 URL만 기재
  lat: number
  lng: number
  features: string[]
}

export const BOXES: CrossFitBox[] = [
  // ===== 서울 =====
  {
    id: 'ultimate-isu',
    name: '얼티밋트레이닝 이수점',
    city: '서울',
    district: '동작구',
    address: '서울특별시 동작구 이수대로 86, 2층',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.4848,
    lng: 126.9817,
    features: ['주차가능', '샤워실', '에어컨', '와이파이'],
  },
  {
    id: 'cfseoul-gangnam',
    name: 'CrossFit Gangnam',
    city: '서울',
    district: '강남구',
    address: '서울특별시 강남구 테헤란로 152 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.5013,
    lng: 127.0396,
    features: ['샤워실', '에어컨', '와이파이'],
  },
  {
    id: 'cfseoul-mapo',
    name: 'CrossFit 501',
    city: '서울',
    district: '마포구',
    address: '서울특별시 마포구 와우산로 29 인근',
    dropinFee: '문의',
    phone: '문의',
    website: 'https://crossfit501.com',
    lat: 37.5568,
    lng: 126.9236,
    features: ['샤워실', '에어컨'],
  },
  {
    id: 'cfseoul-itaewon',
    name: 'CrossFit Itaewon',
    city: '서울',
    district: '용산구',
    address: '서울특별시 용산구 이태원로 143 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.5347,
    lng: 126.9926,
    features: ['샤워실', '에어컨'],
  },
  {
    id: 'cfseoul-songpa',
    name: 'CrossFit Songpa',
    city: '서울',
    district: '송파구',
    address: '서울특별시 송파구 올림픽로 289 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.5148,
    lng: 127.1058,
    features: ['샤워실', '에어컨'],
  },
  {
    id: 'cfseoul-nowon',
    name: 'CrossFit Nowon',
    city: '서울',
    district: '노원구',
    address: '서울특별시 노원구 동일로 1567 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.6542,
    lng: 127.0568,
    features: ['주차가능', '샤워실'],
  },
  {
    id: 'cfseoul-seocho',
    name: 'CrossFit Seocho',
    city: '서울',
    district: '서초구',
    address: '서울특별시 서초구 서초대로 398 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.4830,
    lng: 127.0082,
    features: ['주차가능', '샤워실', '에어컨'],
  },

  // ===== 부산 =====
  {
    id: 'cfbusan-haeundae',
    name: 'CrossFit Haeundae',
    city: '부산',
    district: '해운대구',
    address: '부산광역시 해운대구 해운대해변로 298 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.1588,
    lng: 129.1603,
    features: ['샤워실', '주차가능', '에어컨'],
  },
  {
    id: 'cfbusan-seomyeon',
    name: 'CrossFit Seomyeon',
    city: '부산',
    district: '부산진구',
    address: '부산광역시 부산진구 중앙대로 634 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.1579,
    lng: 129.0596,
    features: ['샤워실', '에어컨'],
  },
  {
    id: 'cfbusan-gwangalli',
    name: 'CrossFit Gwangalli',
    city: '부산',
    district: '수영구',
    address: '부산광역시 수영구 광안해변로 219 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.1530,
    lng: 129.1190,
    features: ['샤워실', '에어컨'],
  },

  // ===== 대구 =====
  {
    id: 'cfdaegu-suseong',
    name: 'CrossFit Suseong',
    city: '대구',
    district: '수성구',
    address: '대구광역시 수성구 달구벌대로 3215 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.8571,
    lng: 128.6320,
    features: ['주차가능', '샤워실', '에어컨'],
  },
  {
    id: 'cfdaegu-jung',
    name: 'CrossFit Daegu Center',
    city: '대구',
    district: '중구',
    address: '대구광역시 중구 동성로 71 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.8682,
    lng: 128.5978,
    features: ['샤워실', '에어컨'],
  },

  // ===== 인천 =====
  {
    id: 'cfincheon-songdo',
    name: 'CrossFit Songdo',
    city: '인천',
    district: '연수구',
    address: '인천광역시 연수구 센트럴로 263 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.4102,
    lng: 126.6782,
    features: ['주차가능', '샤워실', '에어컨'],
  },
  {
    id: 'cfincheon-bupyeong',
    name: 'CrossFit Bupyeong',
    city: '인천',
    district: '부평구',
    address: '인천광역시 부평구 부평대로 168 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.4893,
    lng: 126.7233,
    features: ['샤워실', '에어컨'],
  },

  // ===== 광주 =====
  {
    id: 'cfgwangju-buk',
    name: 'CrossFit Gwangju North',
    city: '광주',
    district: '북구',
    address: '광주광역시 북구 용봉로 77 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.1731,
    lng: 126.9177,
    features: ['주차가능', '샤워실'],
  },
  {
    id: 'cfgwangju-sangmu',
    name: 'CrossFit Sangmu',
    city: '광주',
    district: '서구',
    address: '광주광역시 서구 상무중앙로 110 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.1530,
    lng: 126.8877,
    features: ['샤워실', '에어컨'],
  },

  // ===== 대전 =====
  {
    id: 'cfdaejeon-yuseong',
    name: 'CrossFit Yuseong',
    city: '대전',
    district: '유성구',
    address: '대전광역시 유성구 대학로 99 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 36.3624,
    lng: 127.3566,
    features: ['주차가능', '샤워실'],
  },
  {
    id: 'cfdaejeon-dunsan',
    name: 'CrossFit Dunsan',
    city: '대전',
    district: '서구',
    address: '대전광역시 서구 둔산로 100 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 36.3504,
    lng: 127.3845,
    features: ['샤워실', '에어컨'],
  },

  // ===== 수원 =====
  {
    id: 'cfsuwon-yeongtong',
    name: 'CrossFit Yeongtong',
    city: '수원',
    district: '영통구',
    address: '경기도 수원시 영통구 영통로 234 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 37.2447,
    lng: 127.0551,
    features: ['주차가능', '샤워실', '에어컨'],
  },

  // ===== 울산 =====
  {
    id: 'cfulsan-nam',
    name: 'CrossFit Ulsan South',
    city: '울산',
    district: '남구',
    address: '울산광역시 남구 삼산로 232 인근',
    dropinFee: '문의',
    phone: '문의',
    lat: 35.5384,
    lng: 129.3114,
    features: ['주차가능', '샤워실'],
  },
]
