export interface CrossFitBox {
  id: string
  name: string
  city: string
  district: string
  address: string
  dropinFee: string
  phone: string
  website?: string
  lat: number
  lng: number
  sponsored?: boolean
  features: string[]
}

export const BOXES: CrossFitBox[] = [
  {
    id: 'ultimate-isu',
    name: '얼티밋트레이닝 이수점',
    city: '서울',
    district: '동작구',
    address: '서울특별시 동작구 이수대로 86, 2층 (사당동)',
    dropinFee: '20,000원',
    phone: '02-000-0000',
    lat: 37.4848,
    lng: 126.9817,
    sponsored: true,
    features: ['주차가능', '샤워실', '에어컨', '와이파이', '보충제판매'],
  },
  // ===== Seoul =====
  {
    id: 'cfseoul-gangnam',
    name: 'CrossFit Gangnam',
    city: '서울',
    district: '강남구',
    address: '서울특별시 강남구 테헤란로 152, 2층 (역삼동)',
    dropinFee: '25,000원',
    phone: '02-555-1234',
    website: 'https://cfgangnam.kr',
    lat: 37.5013,
    lng: 127.0396,
    sponsored: true,
    features: ['주차가능', '샤워실', '보충제판매', '개인락커', '에어컨', '와이파이'],
  },
  {
    id: 'cfseoul-mapo',
    name: 'CrossFit 501',
    city: '서울',
    district: '마포구',
    address: '서울특별시 마포구 와우산로 29, 지하 1층 (홍대입구)',
    dropinFee: '20,000원',
    phone: '02-322-5010',
    website: 'https://crossfit501.com',
    lat: 37.5568,
    lng: 126.9236,
    sponsored: true,
    features: ['샤워실', '보충제판매', '주차가능', '와이파이', '에어컨'],
  },
  {
    id: 'cfseoul-itaewon',
    name: 'CrossFit Itaewon',
    city: '서울',
    district: '용산구',
    address: '서울특별시 용산구 이태원로 143, 2층 (이태원동)',
    dropinFee: '20,000원',
    phone: '02-795-7700',
    website: 'https://cfitaewon.com',
    lat: 37.5347,
    lng: 126.9926,
    features: ['샤워실', '에어컨', '와이파이', '보충제판매'],
  },
  {
    id: 'cfseoul-songpa',
    name: 'CrossFit Songpa',
    city: '서울',
    district: '송파구',
    address: '서울특별시 송파구 올림픽로 289, 3층 (방이동)',
    dropinFee: '18,000원',
    phone: '02-416-3200',
    lat: 37.5148,
    lng: 127.1058,
    features: ['샤워실', '개인락커', '에어컨', '보충제판매'],
  },
  {
    id: 'cfseoul-nowon',
    name: 'CrossFit Nowon',
    city: '서울',
    district: '노원구',
    address: '서울특별시 노원구 동일로 1567, 4층 (상계동)',
    dropinFee: '15,000원',
    phone: '02-937-4500',
    lat: 37.6542,
    lng: 127.0568,
    features: ['주차가능', '샤워실', '에어컨'],
  },
  {
    id: 'cfseoul-seocho',
    name: 'CrossFit Seocho',
    city: '서울',
    district: '서초구',
    address: '서울특별시 서초구 서초대로 398, 2층 (서초동)',
    dropinFee: '22,000원',
    phone: '02-584-6600',
    website: 'https://cfseocho.kr',
    lat: 37.4830,
    lng: 127.0082,
    features: ['주차가능', '샤워실', '보충제판매', '개인락커', '에어컨', '와이파이'],
  },

  // ===== Busan =====
  {
    id: 'cfbusan-haeundae',
    name: 'CrossFit Haeundae',
    city: '부산',
    district: '해운대구',
    address: '부산광역시 해운대구 해운대해변로 298, 4층 (우동)',
    dropinFee: '18,000원',
    phone: '051-740-5800',
    website: 'https://cfhaeundae.com',
    lat: 35.1588,
    lng: 129.1603,
    sponsored: true,
    features: ['샤워실', '주차가능', '에어컨', '보충제판매', '와이파이'],
  },
  {
    id: 'cfbusan-seomyeon',
    name: 'CrossFit Seomyeon',
    city: '부산',
    district: '부산진구',
    address: '부산광역시 부산진구 중앙대로 634, 5층 (부전동)',
    dropinFee: '15,000원',
    phone: '051-808-3300',
    lat: 35.1579,
    lng: 129.0596,
    features: ['샤워실', '에어컨', '와이파이'],
  },
  {
    id: 'cfbusan-gwangalli',
    name: 'CrossFit Gwangalli',
    city: '부산',
    district: '수영구',
    address: '부산광역시 수영구 광안해변로 219, 2층 (광안동)',
    dropinFee: '15,000원',
    phone: '051-752-2200',
    lat: 35.1530,
    lng: 129.1190,
    features: ['샤워실', '에어컨', '주차가능'],
  },

  // ===== Daegu =====
  {
    id: 'cfdaegu-suseong',
    name: 'CrossFit Suseong',
    city: '대구',
    district: '수성구',
    address: '대구광역시 수성구 달구벌대로 3215, 2층 (범어동)',
    dropinFee: '15,000원',
    phone: '053-766-8800',
    website: 'https://cfsuseong.kr',
    lat: 35.8571,
    lng: 128.6320,
    features: ['주차가능', '샤워실', '에어컨', '보충제판매'],
  },
  {
    id: 'cfdaegu-jung',
    name: 'CrossFit Daegu Center',
    city: '대구',
    district: '중구',
    address: '대구광역시 중구 동성로 71, 3층 (동성로)',
    dropinFee: '13,000원',
    phone: '053-422-1100',
    lat: 35.8682,
    lng: 128.5978,
    features: ['샤워실', '에어컨'],
  },

  // ===== Incheon =====
  {
    id: 'cfincheon-songdo',
    name: 'CrossFit Songdo',
    city: '인천',
    district: '연수구',
    address: '인천광역시 연수구 센트럴로 263, 6층 (송도동)',
    dropinFee: '18,000원',
    phone: '032-851-7700',
    website: 'https://cfsongdo.com',
    lat: 37.4102,
    lng: 126.6782,
    sponsored: true,
    features: ['주차가능', '샤워실', '에어컨', '보충제판매', '와이파이'],
  },
  {
    id: 'cfincheon-bupyeong',
    name: 'CrossFit Bupyeong',
    city: '인천',
    district: '부평구',
    address: '인천광역시 부평구 부평대로 168, 2층 (부평동)',
    dropinFee: '13,000원',
    phone: '032-510-2200',
    lat: 37.4893,
    lng: 126.7233,
    features: ['샤워실', '에어컨', '주차가능'],
  },

  // ===== Gwangju =====
  {
    id: 'cfgwangju-buk',
    name: 'CrossFit Gwangju North',
    city: '광주',
    district: '북구',
    address: '광주광역시 북구 용봉로 77, 3층 (용봉동)',
    dropinFee: '13,000원',
    phone: '062-511-4400',
    lat: 35.1731,
    lng: 126.9177,
    features: ['주차가능', '샤워실', '에어컨'],
  },
  {
    id: 'cfgwangju-sangmu',
    name: 'CrossFit Sangmu',
    city: '광주',
    district: '서구',
    address: '광주광역시 서구 상무중앙로 110, 2층 (치평동)',
    dropinFee: '12,000원',
    phone: '062-373-5500',
    lat: 35.1530,
    lng: 126.8877,
    features: ['샤워실', '에어컨', '보충제판매'],
  },

  // ===== Daejeon =====
  {
    id: 'cfdaejeon-yuseong',
    name: 'CrossFit Yuseong',
    city: '대전',
    district: '유성구',
    address: '대전광역시 유성구 대학로 99, 4층 (궁동)',
    dropinFee: '13,000원',
    phone: '042-825-9900',
    lat: 36.3624,
    lng: 127.3566,
    features: ['주차가능', '샤워실', '에어컨', '보충제판매'],
  },
  {
    id: 'cfdaejeon-dunsan',
    name: 'CrossFit Dunsan',
    city: '대전',
    district: '서구',
    address: '대전광역시 서구 둔산로 100, 2층 (둔산동)',
    dropinFee: '12,000원',
    phone: '042-488-3300',
    lat: 36.3504,
    lng: 127.3845,
    features: ['샤워실', '에어컨', '와이파이'],
  },

  // ===== Suwon =====
  {
    id: 'cfsuwon-yeongtong',
    name: 'CrossFit Yeongtong',
    city: '수원',
    district: '영통구',
    address: '경기도 수원시 영통구 영통로 234, 2층 (영통동)',
    dropinFee: '15,000원',
    phone: '031-202-5500',
    website: 'https://cfyeongtong.kr',
    lat: 37.2447,
    lng: 127.0551,
    sponsored: true,
    features: ['주차가능', '샤워실', '에어컨', '보충제판매', '와이파이'],
  },

  // ===== Ulsan =====
  {
    id: 'cfulsan-nam',
    name: 'CrossFit Ulsan South',
    city: '울산',
    district: '남구',
    address: '울산광역시 남구 삼산로 232, 3층 (삼산동)',
    dropinFee: '14,000원',
    phone: '052-268-7700',
    lat: 35.5384,
    lng: 129.3114,
    features: ['주차가능', '샤워실', '에어컨', '보충제판매'],
  },
]
