export interface WOD {
  id: string
  name: string
  type: 'girl' | 'hero' | 'open' | 'benchmark'
  equipment: ('barbell' | 'dumbbell' | 'bodyweight' | 'rope' | 'kettlebell' | 'box')[]
  description: string
  movements: string[]
  scaling: string
  timeTarget: string
  rounds?: number
  tags: string[]
}

export const WODS: WOD[] = [
  // ===== GIRL WODs =====
  {
    id: 'fran',
    name: 'Fran',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '21-15-9 반복으로 Thruster와 Pull-up을 최대한 빠르게 완료합니다.\n\n21 Thruster (43kg/30kg)\n21 Pull-up\n15 Thruster\n15 Pull-up\n9 Thruster\n9 Pull-up',
    movements: ['Thruster', 'Pull-up'],
    scaling: '• Thruster 무게: 30kg → 20kg → PVC\n• Pull-up: 밴드 Pull-up → Ring Row → Jumping Pull-up\n• 권장 중량: 첫 세트 21개를 2세트 이하로 분할 가능한 무게',
    timeTarget: '서브 3분 (엘리트), 5분 이하 (경쟁), 10분 이하 (일반)',
    tags: ['21-15-9', 'Pull-up', 'Thruster', '전신운동'],
  },
  {
    id: 'grace',
    name: 'Grace',
    type: 'girl',
    equipment: ['barbell'],
    description: '30개의 Clean & Jerk를 최대한 빠르게 완료합니다.\n\n30 Clean & Jerk (60kg/43kg) for time',
    movements: ['Clean & Jerk'],
    scaling: '• 권장 무게: 45kg → 30kg → 20kg\n• Power Clean + Push Jerk로 대체 가능\n• 분할: 5×6 또는 6×5로 세트 분할 추천',
    timeTarget: '서브 2분 (엘리트), 4분 이하 (경쟁), 7분 이하 (일반)',
    tags: ['Clean & Jerk', 'Barbell', '파워'],
  },
  {
    id: 'helen',
    name: 'Helen',
    type: 'girl',
    equipment: ['kettlebell', 'bodyweight'],
    description: '3라운드를 최대한 빠르게 완료합니다.\n\n400m Run\n21 Kettlebell Swing (24kg/16kg)\n12 Pull-up',
    movements: ['400m Run', 'Kettlebell Swing', 'Pull-up'],
    scaling: '• Kettlebell: 24kg → 16kg → 12kg\n• Pull-up: 밴드 Pull-up → Ring Row\n• Run: 400m Rowing/Bike로 대체 가능',
    timeTarget: '서브 9분 (엘리트), 12분 이하 (경쟁), 15분 이하 (일반)',
    rounds: 3,
    tags: ['Running', 'Kettlebell', 'Pull-up', '3 Rounds'],
  },
  {
    id: 'annie',
    name: 'Annie',
    type: 'girl',
    equipment: ['rope', 'bodyweight'],
    description: '50-40-30-20-10 반복으로 Double-Under와 Sit-up을 최대한 빠르게 완료합니다.\n\n50 Double-Under\n50 Sit-up\n40 Double-Under\n40 Sit-up\n30 Double-Under\n30 Sit-up\n20 Double-Under\n20 Sit-up\n10 Double-Under\n10 Sit-up',
    movements: ['Double-Under', 'Sit-up'],
    scaling: '• Double-Under: 2:1 Single-Under 또는 1:1 Single-Under\n• Sit-up: Anchored Sit-up 또는 Crunch로 대체\n• 줄넘기 없을 경우: Jumping Jack 2:1로 대체',
    timeTarget: '서브 8분 (엘리트), 12분 이하 (경쟁), 18분 이하 (일반)',
    tags: ['Double-Under', 'Sit-up', '줄넘기', '코어'],
  },
  {
    id: 'eva',
    name: 'Eva',
    type: 'girl',
    equipment: ['kettlebell', 'rope', 'bodyweight'],
    description: '5라운드를 최대한 빠르게 완료합니다.\n\n800m Run\n30 Kettlebell Swing (32kg/24kg)\n30 Pull-up',
    movements: ['800m Run', 'Kettlebell Swing', 'Pull-up'],
    scaling: '• Kettlebell: 32kg → 24kg → 16kg\n• Pull-up: 밴드 Pull-up → Ring Row\n• Run: 400m Rowing으로 대체 가능',
    timeTarget: '40분 이하 (엘리트), 50분 이하 (일반)',
    rounds: 5,
    tags: ['Running', 'Kettlebell', 'Pull-up', '지구력'],
  },
  {
    id: 'kelly',
    name: 'Kelly',
    type: 'girl',
    equipment: ['box', 'bodyweight'],
    description: '5라운드를 최대한 빠르게 완료합니다.\n\n400m Run\n30 Box Jump (61cm/51cm)\n30 Wall Ball (9kg/6kg)',
    movements: ['400m Run', 'Box Jump', 'Wall Ball'],
    scaling: '• Box: 61cm → 51cm → 41cm\n• Wall Ball: 9kg → 6kg → 4kg\n• Run: 조깅 페이스 유지',
    timeTarget: '35분 이하 (엘리트), 45분 이하 (일반)',
    rounds: 5,
    tags: ['Running', 'Box Jump', 'Wall Ball', '지구력'],
  },
  {
    id: 'amanda',
    name: 'Amanda',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '9-7-5 반복으로 Ring Muscle-up과 Snatch를 최대한 빠르게 완료합니다.\n\n9 Ring Muscle-up\n9 Snatch (61kg/43kg)\n7 Ring Muscle-up\n7 Snatch\n5 Ring Muscle-up\n5 Snatch',
    movements: ['Ring Muscle-up', 'Snatch'],
    scaling: '• Muscle-up: Chest-to-Bar Pull-up → 밴드 Muscle-up\n• Snatch: 43kg → 30kg → Power Snatch\n• 고급 WOD: 충분한 기술 습득 후 도전',
    timeTarget: '서브 10분 (엘리트), 15분 이하 (경쟁)',
    tags: ['Ring Muscle-up', 'Snatch', '고급', '9-7-5'],
  },
  {
    id: 'isabel',
    name: 'Isabel',
    type: 'girl',
    equipment: ['barbell'],
    description: '30개의 Snatch를 최대한 빠르게 완료합니다.\n\n30 Snatch (61kg/43kg) for time',
    movements: ['Snatch'],
    scaling: '• 권장 무게: 43kg → 30kg → 20kg\n• Power Snatch로 대체 가능\n• 분할: 5×6 또는 6×5 추천',
    timeTarget: '서브 2분 (엘리트), 5분 이하 (경쟁), 8분 이하 (일반)',
    tags: ['Snatch', 'Barbell', '파워'],
  },
  {
    id: 'karen',
    name: 'Karen',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '150개의 Wall Ball Shot을 최대한 빠르게 완료합니다.\n\n150 Wall Ball Shot (9kg/6kg) for time\n타겟 높이: 3m/2.7m',
    movements: ['Wall Ball Shot'],
    scaling: '• Wall Ball: 9kg → 6kg → 4kg\n• 타겟: 높이 조정 가능\n• 분할: 10×15 또는 15×10 추천',
    timeTarget: '서브 8분 (엘리트), 12분 이하 (경쟁), 18분 이하 (일반)',
    tags: ['Wall Ball', '하체', '지구력'],
  },
  {
    id: 'linda',
    name: 'Linda',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '10-9-8-7-6-5-4-3-2-1 반복으로 세 가지 동작을 수행합니다.\n\nDeadlift (체중 1.5배)\nBench Press (체중)\nClean (체중 0.75배)',
    movements: ['Deadlift', 'Bench Press', 'Clean'],
    scaling: '• 각 동작의 무게를 체중 비율에 맞게 조정\n• 체력에 따라 무게 비율 낮춤\n• Bench Press: Floor Press로 대체 가능',
    timeTarget: '20분 이하 (엘리트), 35분 이하 (일반)',
    tags: ['Deadlift', 'Bench Press', 'Clean', '파워리프팅'],
  },
  {
    id: 'mary',
    name: 'Mary',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '20분 AMRAP으로 최대한 많은 라운드를 완료합니다.\n\n5 Handstand Push-up\n10 Pistol Squat (한발 스쿼트)\n15 Pull-up',
    movements: ['Handstand Push-up', 'Pistol Squat', 'Pull-up'],
    scaling: '• HSPU: Pike Push-up → Box Pike\n• Pistol: 박스 보조 Pistol → Split Squat\n• Pull-up: 밴드 Pull-up → Ring Row',
    timeTarget: '20분 AMRAP - 10라운드+ (엘리트), 6라운드+ (경쟁)',
    tags: ['AMRAP', 'Bodyweight', '균형', '고급'],
  },
  {
    id: 'nancy',
    name: 'Nancy',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '5라운드를 최대한 빠르게 완료합니다.\n\n400m Run\n15 Overhead Squat (43kg/30kg)',
    movements: ['400m Run', 'Overhead Squat'],
    scaling: '• OHS: 43kg → 30kg → 20kg → PVC\n• Run: Rowing/Bike 400m 대체 가능\n• 유연성과 안정성 먼저 확인',
    timeTarget: '서브 15분 (엘리트), 20분 이하 (경쟁), 28분 이하 (일반)',
    rounds: 5,
    tags: ['Running', 'OHS', 'Overhead', '5 Rounds'],
  },
  {
    id: 'diane',
    name: 'Diane',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '21-15-9 반복으로 Deadlift와 Handstand Push-up을 완료합니다.\n\n21 Deadlift (100kg/70kg)\n21 Handstand Push-up\n15 Deadlift\n15 Handstand Push-up\n9 Deadlift\n9 Handstand Push-up',
    movements: ['Deadlift', 'Handstand Push-up'],
    scaling: '• Deadlift: 100kg → 70kg → 50kg\n• HSPU: Pike Push-up → Box Pike → Push-up\n• HSPU 벽 보조 사용 가능',
    timeTarget: '서브 4분 (엘리트), 8분 이하 (경쟁), 15분 이하 (일반)',
    tags: ['21-15-9', 'Deadlift', 'HSPU', '파워'],
  },
  {
    id: 'barbara',
    name: 'Barbara',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '5라운드, 각 라운드 후 3분 휴식.\n\n20 Pull-up\n30 Push-up\n40 Sit-up\n50 Air Squat\n(각 라운드 후 3분 휴식)',
    movements: ['Pull-up', 'Push-up', 'Sit-up', 'Air Squat'],
    scaling: '• Pull-up: 밴드 Pull-up → Ring Row\n• Push-up: Knee Push-up\n• 제한시간: 각 라운드 20분 이내',
    timeTarget: '20분 이하 (엘리트), 각 라운드 4분 이하',
    rounds: 5,
    tags: ['Bodyweight', 'Pull-up', '5 Rounds', '근지구력'],
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '30분 EMOM (매 분마다 시작)\n\n매 분: 5 Pull-up + 10 Push-up + 15 Air Squat\n남은 시간은 휴식',
    movements: ['Pull-up', 'Push-up', 'Air Squat'],
    scaling: '• Pull-up: 밴드 Pull-up → Ring Row\n• 각 분에 완료하지 못하면 다음 분에 이어서\n• 30분 완주 목표',
    timeTarget: '30분 EMOM 완주 목표',
    tags: ['EMOM', 'Bodyweight', '30분', '지구력'],
  },
  {
    id: 'cindy',
    name: 'Cindy',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '20분 AMRAP으로 최대한 많은 라운드를 완료합니다.\n\n5 Pull-up\n10 Push-up\n15 Air Squat',
    movements: ['Pull-up', 'Push-up', 'Air Squat'],
    scaling: '• Pull-up: 밴드 Pull-up → Ring Row → Inverted Row\n• Push-up: Knee Push-up\n• 맨몸 입문 WOD로 추천',
    timeTarget: '20분 AMRAP - 20라운드+ (엘리트), 12라운드+ (경쟁), 8라운드+ (일반)',
    tags: ['AMRAP', '20분', 'Bodyweight', '입문'],
  },
  {
    id: 'elizabeth',
    name: 'Elizabeth',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '21-15-9 반복으로 Clean과 Ring Dip을 완료합니다.\n\n21 Clean (61kg/43kg)\n21 Ring Dip\n15 Clean\n15 Ring Dip\n9 Clean\n9 Ring Dip',
    movements: ['Clean', 'Ring Dip'],
    scaling: '• Clean: 61kg → 43kg → 30kg\n• Ring Dip: 밴드 Ring Dip → Box Dip → Parallel Bar Dip\n• Ring Dip 대체: Bar Dips',
    timeTarget: '서브 6분 (엘리트), 10분 이하 (경쟁), 16분 이하 (일반)',
    tags: ['21-15-9', 'Clean', 'Ring Dip', '상체'],
  },
  {
    id: 'jackie',
    name: 'Jackie',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '최대한 빠르게 완료합니다.\n\n1000m Row\n50 Thruster (20kg)\n30 Pull-up',
    movements: ['1000m Row', 'Thruster', 'Pull-up'],
    scaling: '• Rowing: 1000m Run으로 대체 가능\n• Thruster: 20kg → 15kg → PVC\n• Pull-up: 밴드 Pull-up → Ring Row',
    timeTarget: '서브 8분 (엘리트), 12분 이하 (경쟁), 18분 이하 (일반)',
    tags: ['Rowing', 'Thruster', 'Pull-up', '유산소'],
  },
  {
    id: 'lynne',
    name: 'Lynne',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '5라운드, 각 동작 최대 반복 (시간 제한 없음)\n\nBench Press (체중)\nPull-up (최대)',
    movements: ['Bench Press', 'Pull-up'],
    scaling: '• Bench Press: 체중 → 체중의 75% → 체중의 50%\n• Pull-up: 밴드 Pull-up → Ring Row\n• 스코어: 총 반복수 합계',
    timeTarget: '스코어 기반 - 총 반복수 150+ (엘리트)',
    rounds: 5,
    tags: ['근력', 'Bench Press', 'Pull-up', 'Max Reps'],
  },
  {
    id: 'nicole',
    name: 'Nicole',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '20분 AMRAP\n\n400m Run\n최대 Pull-up\n\n(매 라운드마다 이전 Pull-up 개수를 넘지 않으면 다음 라운드 시작)',
    movements: ['400m Run', 'Pull-up'],
    scaling: '• Pull-up: 밴드 Pull-up → Ring Row\n• Run: 조깅 페이스 유지\n• 스코어: 총 Pull-up 개수',
    timeTarget: '20분 AMRAP - 총 Pull-up 100개+ (엘리트)',
    tags: ['AMRAP', 'Running', 'Pull-up', '지구력'],
  },

  // ===== HERO WODs =====
  {
    id: 'murph',
    name: 'Murph',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 해군 중위 마이클 머피를 추모하는 WOD.\n\n1 Mile Run\n100 Pull-up\n200 Push-up\n300 Air Squat\n1 Mile Run\n\n*Partition 허용 (예: 20라운드 × 5 Pull-up+10 Push-up+15 Air Squat)\n**20파운드 조끼/배낭 착용 권장',
    movements: ['1 Mile Run', 'Pull-up', 'Push-up', 'Air Squat'],
    scaling: '• Pull-up: 밴드 Pull-up → Ring Row\n• 조끼 없이 맨몸으로 시작\n• Partition: 20라운드 치퍼 형식 추천\n• Run: 800m로 줄이기 가능',
    timeTarget: '서브 40분 (엘리트), 55분 이하 (경쟁), 70분 이하 (일반)',
    tags: ['Hero', 'Memorial', '지구력', 'Bodyweight', 'Vest'],
  },
  {
    id: 'dt',
    name: 'DT',
    type: 'hero',
    equipment: ['barbell'],
    description: '미 공군 상병 티모시 데이비스를 추모하는 WOD.\n\n5라운드 for time:\n12 Deadlift (70kg/47.5kg)\n9 Hang Power Clean\n6 Push Jerk',
    movements: ['Deadlift', 'Hang Power Clean', 'Push Jerk'],
    scaling: '• 권장 무게: 70kg → 50kg → 35kg\n• 바벨을 내려놓지 않고 연결 동작 권장\n• 무게 조정 시 세 동작 모두 동일 무게',
    timeTarget: '서브 7분 (엘리트), 10분 이하 (경쟁), 15분 이하 (일반)',
    rounds: 5,
    tags: ['Hero', 'Barbell', '5 Rounds', '파워'],
  },
  {
    id: 'michael',
    name: 'Michael',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 해군 소위 마이클 맥게버른을 추모하는 WOD.\n\n3라운드 for time:\n800m Run\n50 Back Extension\n50 Sit-up',
    movements: ['800m Run', 'Back Extension', 'Sit-up'],
    scaling: '• Back Extension: GHD Back Extension 또는 Superman\n• Run: Rowing 800m 대체 가능\n• Sit-up: Anchored Sit-up 가능',
    timeTarget: '서브 20분 (엘리트), 28분 이하 (경쟁)',
    rounds: 3,
    tags: ['Hero', 'Running', 'Core', '3 Rounds'],
  },
  {
    id: 'jt',
    name: 'JT',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 해군 특수부대원 제프 테일러를 추모하는 WOD.\n\n21-15-9 for time:\nHandstand Push-up\nRing Dip\nPush-up',
    movements: ['Handstand Push-up', 'Ring Dip', 'Push-up'],
    scaling: '• HSPU: Pike Push-up → Box Pike\n• Ring Dip: 밴드 Ring Dip → Box Dip\n• 상체 근력 WOD',
    timeTarget: '서브 8분 (엘리트), 15분 이하 (경쟁)',
    tags: ['Hero', '21-15-9', '상체', 'Bodyweight'],
  },
  {
    id: 'randy',
    name: 'Randy',
    type: 'hero',
    equipment: ['barbell'],
    description: '미 공군 특수요원 랜디 하드을 추모하는 WOD.\n\n75 Power Snatch (35kg) for time',
    movements: ['Power Snatch'],
    scaling: '• 권장 무게: 35kg → 25kg → 15kg\n• 분할: 5×15 또는 10×7~8\n• 기술 WOD: Snatch 동작 완벽히 숙지 후 도전',
    timeTarget: '서브 6분 (엘리트), 10분 이하 (경쟁), 15분 이하 (일반)',
    tags: ['Hero', 'Snatch', 'Barbell', '반복'],
  },
  {
    id: 'ryan',
    name: 'Ryan',
    type: 'hero',
    equipment: ['box', 'barbell'],
    description: '미 육군 레인저 라이언 잡을 추모하는 WOD.\n\n5라운드 for time:\n7 Ring Muscle-up\n21 Burpee Box Jump (61cm)',
    movements: ['Ring Muscle-up', 'Burpee Box Jump'],
    scaling: '• Muscle-up: Chest-to-Bar Pull-up → 밴드 Muscle-up\n• Burpee Box: Burpee + Step-up으로 대체\n• 고강도 WOD',
    timeTarget: '서브 20분 (엘리트), 30분 이하 (경쟁)',
    rounds: 5,
    tags: ['Hero', 'Muscle-up', 'Burpee', '5 Rounds'],
  },
  {
    id: 'holleyman',
    name: 'Holleyman',
    type: 'hero',
    equipment: ['barbell', 'bodyweight', 'box'],
    description: '미 육군 특전사 아론 홀레이만을 추모하는 WOD.\n\n30라운드 for time:\n5 Power Clean (70kg)\n3 Handstand Push-up\n1 Ring Muscle-up',
    movements: ['Power Clean', 'Handstand Push-up', 'Ring Muscle-up'],
    scaling: '• Power Clean: 70kg → 50kg → 35kg\n• HSPU: Pike Push-up\n• Muscle-up: Chest-to-Bar Pull-up 2개\n• 30라운드 완주 목표',
    timeTarget: '40분 이하 (엘리트), 55분 이하 (경쟁)',
    rounds: 30,
    tags: ['Hero', '30 Rounds', '고급', 'Chipper'],
  },
  {
    id: 'kalsu',
    name: 'Kalsu',
    type: 'hero',
    equipment: ['barbell'],
    description: '미 NFL 선수 밥 칼수를 추모하는 WOD.\n\n100 Thruster (60kg/43kg) for time\n매 분 시작 시: 5 Burpee 수행\n(타이머 시작 시 5 Burpee로 시작)',
    movements: ['Thruster', 'Burpee'],
    scaling: '• 권장 무게: 60kg → 43kg → 30kg\n• Burpee 먼저 수행 후 남은 시간 Thruster\n• 가장 힘든 WOD 중 하나',
    timeTarget: '20분 이하 (엘리트), 30분 이하 (경쟁)',
    tags: ['Hero', 'Thruster', 'Burpee', 'EMOM 혼합'],
  },
  {
    id: 'jason',
    name: 'Jason',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 육군 스태프 상사 제이슨 고든을 추모하는 WOD.\n\n100 Air Squat\n5 Ring Muscle-up\n75 Air Squat\n10 Ring Muscle-up\n50 Air Squat\n15 Ring Muscle-up\n25 Air Squat\n20 Ring Muscle-up',
    movements: ['Air Squat', 'Ring Muscle-up'],
    scaling: '• Muscle-up: Chest-to-Bar Pull-up 2:1\n• Air Squat: 낮은 고관절 깊이 유지\n• Chipper 형식',
    timeTarget: '20분 이하 (엘리트), 30분 이하 (경쟁)',
    tags: ['Hero', 'Chipper', 'Muscle-up', 'Squat'],
  },
  {
    id: 'danny',
    name: 'Danny',
    type: 'hero',
    equipment: ['box', 'barbell', 'bodyweight'],
    description: '미 육군 병사 대니 디에즈를 추모하는 WOD.\n\n20분 AMRAP:\n30 Box Jump (61cm)\n20 Push Press (52.5kg)\n30 Pull-up',
    movements: ['Box Jump', 'Push Press', 'Pull-up'],
    scaling: '• Box: 61cm → 51cm → 41cm\n• Push Press: 52.5kg → 35kg → 22.5kg\n• Pull-up: 밴드 Pull-up → Ring Row',
    timeTarget: '20분 AMRAP - 5라운드+ (엘리트), 3라운드+ (경쟁)',
    tags: ['Hero', 'AMRAP', '20분', 'Box Jump'],
  },

  // ===== CrossFit Open WODs =====
  {
    id: 'open-11-1',
    name: '11.1',
    type: 'open',
    equipment: ['rope', 'bodyweight'],
    description: '10분 AMRAP:\n30 Double-Under\n15 Power Snatch (35kg/25kg)',
    movements: ['Double-Under', 'Power Snatch'],
    scaling: '• Double-Under: 2:1 Single-Under\n• Snatch: 35kg → 25kg → 15kg',
    timeTarget: '10분 AMRAP - 10라운드+ (엘리트)',
    tags: ['Open', '2011', 'AMRAP', 'Double-Under'],
  },
  {
    id: 'open-12-1',
    name: '12.1',
    type: 'open',
    equipment: ['bodyweight'],
    description: '7분 AMRAP:\nBurpee',
    movements: ['Burpee'],
    scaling: '• 기준 동작 엄격하게 적용\n• 점프 후 양손 박수 확인\n• 100개+ 목표 (엘리트)',
    timeTarget: '7분 AMRAP - 100개+ (엘리트), 75개+ (경쟁)',
    tags: ['Open', '2012', 'AMRAP', 'Burpee'],
  },
  {
    id: 'open-13-1',
    name: '13.1',
    type: 'open',
    equipment: ['barbell', 'rope'],
    description: '17분 AMRAP:\n40 Burpee Box Jump (50cm)\n30 Snatch (35kg/25kg)\n30 Burpee Box Jump\n30 Snatch (60kg/42.5kg)\n20 Burpee Box Jump\n30 Snatch (102.5kg/70kg)\n10 Burpee Box Jump\n최대 Snatch (145kg/102.5kg)',
    movements: ['Burpee Box Jump', 'Snatch'],
    scaling: '• 각 무게 단계별 스케일링\n• 시간 내 최대한 진행',
    timeTarget: '17분 AMRAP',
    tags: ['Open', '2013', 'Snatch', 'Chipper'],
  },
  {
    id: 'open-14-1',
    name: '14.1',
    type: 'open',
    equipment: ['rope', 'barbell'],
    description: '10분 AMRAP:\n30 Double-Under\n15 Power Snatch (35kg/25kg)',
    movements: ['Double-Under', 'Power Snatch'],
    scaling: '• Double-Under: 2:1 Single-Under\n• Snatch: 35kg → 25kg',
    timeTarget: '10분 AMRAP',
    tags: ['Open', '2014', 'AMRAP', 'Double-Under'],
  },
  {
    id: 'open-15-1',
    name: '15.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '9분 AMRAP:\n15 Toes-to-Bar\n10 Deadlift (70kg/47.5kg)\n5 Snatch (70kg/47.5kg)\n\n이후 6분 내 1RM Clean & Jerk',
    movements: ['Toes-to-Bar', 'Deadlift', 'Snatch', 'Clean & Jerk'],
    scaling: '• 무게 스케일링 가능\n• Clean & Jerk 1RM 기록',
    timeTarget: '9분 AMRAP + 6분 1RM',
    tags: ['Open', '2015', 'AMRAP', '1RM'],
  },
  {
    id: 'open-16-1',
    name: '16.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '20분 AMRAP:\n25피트 Overhead Walking Lunge (43kg/30kg)\n8 Burpee Box Jump (50cm)\n25피트 Overhead Walking Lunge\n8 Chest-to-Bar Pull-up',
    movements: ['Overhead Walking Lunge', 'Burpee Box Jump', 'Chest-to-Bar Pull-up'],
    scaling: '• Lunge 무게: 43kg → 20kg\n• Chest-to-Bar: Jumping Pull-up → Ring Row',
    timeTarget: '20분 AMRAP',
    tags: ['Open', '2016', 'AMRAP', 'Lunge'],
  },
  {
    id: 'open-17-1',
    name: '17.1',
    type: 'open',
    equipment: ['dumbbell', 'bodyweight'],
    description: '20분 AMRAP:\n10 Dumbbell Snatch (22.5kg/15kg)\n15 Box Jump Over (50cm)',
    movements: ['Dumbbell Snatch', 'Box Jump Over'],
    scaling: '• Dumbbell: 22.5kg → 15kg → 10kg\n• Box: 50cm → 41cm → 24cm\n• Dumbbell Open의 시작',
    timeTarget: '20분 AMRAP',
    tags: ['Open', '2017', 'AMRAP', 'Dumbbell'],
  },
  {
    id: 'open-18-1',
    name: '18.1',
    type: 'open',
    equipment: ['dumbbell', 'bodyweight'],
    description: '20분 AMRAP:\n8 Toes-to-Bar\n10 Hand-Release Push-up\n12 Dumbbell Snatch (22.5kg/15kg)',
    movements: ['Toes-to-Bar', 'Hand-Release Push-up', 'Dumbbell Snatch'],
    scaling: '• Dumbbell: 22.5kg → 15kg → 10kg\n• Toes-to-Bar: Knees-to-Chest → Sit-up',
    timeTarget: '20분 AMRAP',
    tags: ['Open', '2018', 'AMRAP', 'Dumbbell'],
  },
  {
    id: 'open-19-1',
    name: '19.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '15분 AMRAP:\n19 Wall Ball (9kg/6kg)\n19 Caulsnider (50cm)',
    movements: ['Wall Ball', 'Caulsnider'],
    scaling: '• Wall Ball: 9kg → 6kg → 4kg\n• Caulsnider: Burpee + Box Jump Over\n• Box: 50cm → 41cm',
    timeTarget: '15분 AMRAP',
    tags: ['Open', '2019', 'AMRAP', 'Wall Ball'],
  },
  {
    id: 'open-20-1',
    name: '20.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '10라운드 for time (8분 제한):\n8 Ground-to-Overhead (43kg/29kg)\n10 Bar Facing Burpee',
    movements: ['Ground-to-Overhead', 'Bar Facing Burpee'],
    scaling: '• 무게: 43kg → 29kg → 20kg\n• Burpee: 스텝 업/다운 가능',
    timeTarget: '8분 이내 10라운드',
    tags: ['Open', '2020', 'Burpee', 'GTO'],
  },
  {
    id: 'open-21-1',
    name: '21.1',
    type: 'open',
    equipment: ['rope', 'barbell'],
    description: '15분 AMRAP:\n21 Double-Under\n15 Power Snatch (25kg)\n9 Bar Muscle-up',
    movements: ['Double-Under', 'Power Snatch', 'Bar Muscle-up'],
    scaling: '• Double-Under: 2:1 Single-Under\n• Snatch: 25kg → 15kg\n• Muscle-up: Chest-to-Bar Pull-up',
    timeTarget: '15분 AMRAP',
    tags: ['Open', '2021', 'AMRAP', 'Double-Under'],
  },
  {
    id: 'open-22-1',
    name: '22.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '15분 AMRAP:\n3 Wall Walk (4.5m)\n3 Ring Muscle-up\n3 Power Snatch (43kg)',
    movements: ['Wall Walk', 'Ring Muscle-up', 'Power Snatch'],
    scaling: '• Wall Walk: Inchworm → Pike Push-up\n• Muscle-up: Chest-to-Bar Pull-up\n• Snatch: 43kg → 29kg → 20kg',
    timeTarget: '15분 AMRAP',
    tags: ['Open', '2022', 'AMRAP', '고급'],
  },
  {
    id: 'open-23-1',
    name: '23.1',
    type: 'open',
    equipment: ['barbell', 'rope', 'bodyweight'],
    description: '14분 AMRAP:\n60 Cal Row\n50 Thruster (20kg)\n40 Single-Under\n30 Sit-up\n20 Power Clean & Jerk (43kg)\n10 Double-Under',
    movements: ['Row', 'Thruster', 'Single-Under', 'Sit-up', 'Power Clean & Jerk', 'Double-Under'],
    scaling: '• 각 무게 스케일링 가능\n• Rowing: Bike Erg 대체 가능\n• 시간 내 최대한 진행',
    timeTarget: '14분 AMRAP',
    tags: ['Open', '2023', 'AMRAP', 'Chipper'],
  },
]

export const WOD_CATEGORIES = [
  { id: 'all', label: '전체' },
  { id: 'girl', label: 'Girl WODs' },
  { id: 'hero', label: 'Hero WODs' },
  { id: 'open', label: 'CrossFit Open' },
  { id: 'benchmark', label: '벤치마크' },
]

export const EQUIPMENT_FILTERS = [
  { id: 'all', label: '전체' },
  { id: 'barbell', label: '바벨' },
  { id: 'dumbbell', label: '덤벨' },
  { id: 'bodyweight', label: '맨몸' },
  { id: 'kettlebell', label: '케틀벨' },
  { id: 'rope', label: '줄넘기' },
  { id: 'box', label: '박스' },
]
