export interface WOD {
  id: string
  name: string
  type: 'girl' | 'hero' | 'open' | 'benchmark'
  equipment: ('barbell' | 'dumbbell' | 'bodyweight' | 'rope' | 'kettlebell' | 'box')[]
  description: string
  movements: string[]
  scaling: string
  timeTarget: string
  rounds?: number
  tags: string[]
}

export const WODS: WOD[] = [
  // ===== GIRL WODs =====
  {
    id: 'fran',
    name: 'Fran',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '21-15-9 반복으로 쓰러스터와 풀업을 최대한 빠르게 완료합니다.\n\n21 쓰러스터 (43kg/30kg)\n21 풀업\n15 쓰러스터\n15 풀업\n9 쓰러스터\n9 풀업',
    movements: ['쓰러스터', '풀업'],
    scaling: '• 쓰러스터 무게: 30kg → 20kg → PVC\n• 풀업: 밴드 풀업 → 링 로우 → 점핑 풀업\n• 권장 중량: 첫 세트 21개를 2세트 이하로 분할 가능한 무게',
    timeTarget: '서브 3분 (엘리트), 5분 이하 (경쟁), 10분 이하 (일반)',
    tags: ['21-15-9', '풀업', '쓰러스터', '전신운동'],
  },
  {
    id: 'grace',
    name: 'Grace',
    type: 'girl',
    equipment: ['barbell'],
    description: '30개의 클린 앤 저크를 최대한 빠르게 완료합니다.\n\n30 클린 앤 저크 (60kg/43kg) for time',
    movements: ['클린 앤 저크'],
    scaling: '• 권장 무게: 45kg → 30kg → 20kg\n• 파워 클린 + 푸시 저크로 대체 가능\n• 분할: 5×6 또는 6×5로 세트 분할 추천',
    timeTarget: '서브 2분 (엘리트), 4분 이하 (경쟁), 7분 이하 (일반)',
    tags: ['클린앤저크', '바벨', '파워'],
  },
  {
    id: 'helen',
    name: 'Helen',
    type: 'girl',
    equipment: ['kettlebell', 'bodyweight'],
    description: '3라운드를 최대한 빠르게 완료합니다.\n\n400m 런\n21 케틀벨 스윙 (24kg/16kg)\n12 풀업',
    movements: ['400m 런', '케틀벨 스윙', '풀업'],
    scaling: '• 케틀벨: 24kg → 16kg → 12kg\n• 풀업: 밴드 풀업 → 링 로우\n• 런: 400m 로잉/바이크로 대체 가능',
    timeTarget: '서브 9분 (엘리트), 12분 이하 (경쟁), 15분 이하 (일반)',
    rounds: 3,
    tags: ['런닝', '케틀벨', '풀업', '3라운드'],
  },
  {
    id: 'annie',
    name: 'Annie',
    type: 'girl',
    equipment: ['rope', 'bodyweight'],
    description: '50-40-30-20-10 반복으로 더블언더와 싯업을 최대한 빠르게 완료합니다.\n\n50 더블언더\n50 싯업\n40 더블언더\n40 싯업\n30 더블언더\n30 싯업\n20 더블언더\n20 싯업\n10 더블언더\n10 싯업',
    movements: ['더블언더', '싯업'],
    scaling: '• 더블언더: 2:1 싱글언더 또는 1:1 싱글언더\n• 싯업: 앵커드 싯업 또는 크런치로 대체\n• 줄넘기 없을 경우: 점프잭 2:1로 대체',
    timeTarget: '서브 8분 (엘리트), 12분 이하 (경쟁), 18분 이하 (일반)',
    tags: ['더블언더', '싯업', '줄넘기', '코어'],
  },
  {
    id: 'eva',
    name: 'Eva',
    type: 'girl',
    equipment: ['kettlebell', 'rope', 'bodyweight'],
    description: '5라운드를 최대한 빠르게 완료합니다.\n\n800m 런\n30 케틀벨 스윙 (32kg/24kg)\n30 풀업',
    movements: ['800m 런', '케틀벨 스윙', '풀업'],
    scaling: '• 케틀벨: 32kg → 24kg → 16kg\n• 풀업: 밴드 풀업 → 링 로우\n• 런: 400m 로잉으로 대체 가능',
    timeTarget: '40분 이하 (엘리트), 50분 이하 (일반)',
    rounds: 5,
    tags: ['런닝', '케틀벨', '풀업', '지구력'],
  },
  {
    id: 'kelly',
    name: 'Kelly',
    type: 'girl',
    equipment: ['box', 'bodyweight'],
    description: '5라운드를 최대한 빠르게 완료합니다.\n\n400m 런\n30 박스 점프 (61cm/51cm)\n30 월볼 (9kg/6kg)',
    movements: ['400m 런', '박스 점프', '월볼'],
    scaling: '• 박스: 61cm → 51cm → 41cm\n• 월볼: 9kg → 6kg → 4kg\n• 런: 조깅 페이스 유지',
    timeTarget: '35분 이하 (엘리트), 45분 이하 (일반)',
    rounds: 5,
    tags: ['런닝', '박스점프', '월볼', '지구력'],
  },
  {
    id: 'amanda',
    name: 'Amanda',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '9-7-5 반복으로 머슬업과 스내치를 최대한 빠르게 완료합니다.\n\n9 링 머슬업\n9 스내치 (61kg/43kg)\n7 링 머슬업\n7 스내치\n5 링 머슬업\n5 스내치',
    movements: ['링 머슬업', '스내치'],
    scaling: '• 머슬업: 체스트 투 바 풀업 → 밴드 머슬업\n• 스내치: 43kg → 30kg → 파워 스내치\n• 고급 WOD: 충분한 기술 습득 후 도전',
    timeTarget: '서브 10분 (엘리트), 15분 이하 (경쟁)',
    tags: ['링머슬업', '스내치', '고급', '9-7-5'],
  },
  {
    id: 'isabel',
    name: 'Isabel',
    type: 'girl',
    equipment: ['barbell'],
    description: '30개의 스내치를 최대한 빠르게 완료합니다.\n\n30 스내치 (61kg/43kg) for time',
    movements: ['스내치'],
    scaling: '• 권장 무게: 43kg → 30kg → 20kg\n• 파워 스내치로 대체 가능\n• 분할: 5×6 또는 6×5 추천',
    timeTarget: '서브 2분 (엘리트), 5분 이하 (경쟁), 8분 이하 (일반)',
    tags: ['스내치', '바벨', '파워'],
  },
  {
    id: 'karen',
    name: 'Karen',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '150개의 월볼 샷을 최대한 빠르게 완료합니다.\n\n150 월볼 샷 (9kg/6kg) for time\n타겟 높이: 3m/2.7m',
    movements: ['월볼 샷'],
    scaling: '• 월볼: 9kg → 6kg → 4kg\n• 타겟: 높이 조정 가능\n• 분할: 10×15 또는 15×10 추천',
    timeTarget: '서브 8분 (엘리트), 12분 이하 (경쟁), 18분 이하 (일반)',
    tags: ['월볼', '레그', '지구력'],
  },
  {
    id: 'linda',
    name: 'Linda',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '10-9-8-7-6-5-4-3-2-1 반복으로 세 가지 동작을 수행합니다.\n\n데드리프트 (체중 1.5배)\n벤치 프레스 (체중)\n클린 (체중 0.75배)',
    movements: ['데드리프트', '벤치 프레스', '클린'],
    scaling: '• 각 동작의 무게를 체중 비율에 맞게 조정\n• 체력에 따라 무게 비율 낮춤\n• 벤치 프레스: 플로어 프레스로 대체 가능',
    timeTarget: '20분 이하 (엘리트), 35분 이하 (일반)',
    tags: ['데드리프트', '벤치프레스', '클린', '파워리프팅'],
  },
  {
    id: 'mary',
    name: 'Mary',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '20분 AMRAP으로 최대한 많은 라운드를 완료합니다.\n\n5 핸드스탠드 푸시업\n10 피스톨 스쿼트 (한발 스쿼트)\n15 풀업',
    movements: ['핸드스탠드 푸시업', '피스톨 스쿼트', '풀업'],
    scaling: '• HSPU: 파이크 푸시업 → 박스 파이크\n• 피스톨: 박스 보조 피스톨 → 스플릿 스쿼트\n• 풀업: 밴드 풀업 → 링 로우',
    timeTarget: '20분 AMRAP - 10라운드+ (엘리트), 6라운드+ (경쟁)',
    tags: ['AMRAP', '맨몸', '균형', '고급'],
  },
  {
    id: 'nancy',
    name: 'Nancy',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '5라운드를 최대한 빠르게 완료합니다.\n\n400m 런\n15 오버헤드 스쿼트 (43kg/30kg)',
    movements: ['400m 런', '오버헤드 스쿼트'],
    scaling: '• OHS: 43kg → 30kg → 20kg → PVC\n• 런: 로잉/바이크 400m 대체 가능\n• 유연성과 안정성 먼저 확인',
    timeTarget: '서브 15분 (엘리트), 20분 이하 (경쟁), 28분 이하 (일반)',
    rounds: 5,
    tags: ['런닝', 'OHS', '오버헤드', '5라운드'],
  },
  {
    id: 'diane',
    name: 'Diane',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '21-15-9 반복으로 데드리프트와 핸드스탠드 푸시업을 완료합니다.\n\n21 데드리프트 (100kg/70kg)\n21 핸드스탠드 푸시업\n15 데드리프트\n15 핸드스탠드 푸시업\n9 데드리프트\n9 핸드스탠드 푸시업',
    movements: ['데드리프트', '핸드스탠드 푸시업'],
    scaling: '• 데드리프트: 100kg → 70kg → 50kg\n• HSPU: 파이크 푸시업 → 박스 파이크 → 일반 푸시업\n• HSPU 벽 보조 사용 가능',
    timeTarget: '서브 4분 (엘리트), 8분 이하 (경쟁), 15분 이하 (일반)',
    tags: ['21-15-9', '데드리프트', 'HSPU', '파워'],
  },
  {
    id: 'barbara',
    name: 'Barbara',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '5라운드, 각 라운드 후 3분 휴식.\n\n20 풀업\n30 푸시업\n40 싯업\n50 에어 스쿼트\n(각 라운드 후 3분 휴식)',
    movements: ['풀업', '푸시업', '싯업', '에어 스쿼트'],
    scaling: '• 풀업: 밴드 풀업 → 링 로우\n• 푸시업: 무릎 푸시업\n• 제한시간: 각 라운드 20분 이내',
    timeTarget: '20분 이하 (엘리트), 각 라운드 4분 이하',
    rounds: 5,
    tags: ['맨몸', '풀업', '5라운드', '근지구력'],
  },
  {
    id: 'chelsea',
    name: 'Chelsea',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '30분 EMOM (매 분마다 시작)\n\n매 분: 5 풀업 + 10 푸시업 + 15 스쿼트\n남은 시간은 휴식',
    movements: ['풀업', '푸시업', '에어 스쿼트'],
    scaling: '• 풀업: 밴드 풀업 → 링 로우\n• 각 분에 완료하지 못하면 다음 분에 이어서\n• 30분 완주 목표',
    timeTarget: '30분 EMOM 완주 목표',
    tags: ['EMOM', '맨몸', '30분', '지구력'],
  },
  {
    id: 'cindy',
    name: 'Cindy',
    type: 'girl',
    equipment: ['bodyweight'],
    description: '20분 AMRAP으로 최대한 많은 라운드를 완료합니다.\n\n5 풀업\n10 푸시업\n15 에어 스쿼트',
    movements: ['풀업', '푸시업', '에어 스쿼트'],
    scaling: '• 풀업: 밴드 풀업 → 링 로우 → 인버티드 로우\n• 푸시업: 무릎 푸시업\n• 맨몸 입문 WOD로 추천',
    timeTarget: '20분 AMRAP - 20라운드+ (엘리트), 12라운드+ (경쟁), 8라운드+ (일반)',
    tags: ['AMRAP', '20분', '맨몸', '입문'],
  },
  {
    id: 'elizabeth',
    name: 'Elizabeth',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '21-15-9 반복으로 클린과 링딥을 완료합니다.\n\n21 클린 (61kg/43kg)\n21 링딥\n15 클린\n15 링딥\n9 클린\n9 링딥',
    movements: ['클린', '링딥'],
    scaling: '• 클린: 61kg → 43kg → 30kg\n• 링딥: 밴드 링딥 → 박스딥 → 파라렛딥\n• 링딥 대체: 바 딥스',
    timeTarget: '서브 6분 (엘리트), 10분 이하 (경쟁), 16분 이하 (일반)',
    tags: ['21-15-9', '클린', '링딥', '상체'],
  },
  {
    id: 'jackie',
    name: 'Jackie',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '최대한 빠르게 완료합니다.\n\n1000m 로잉\n50 쓰러스터 (20kg)\n30 풀업',
    movements: ['1000m 로잉', '쓰러스터', '풀업'],
    scaling: '• 로잉: 1000m 런으로 대체 가능\n• 쓰러스터: 20kg → 15kg → PVC\n• 풀업: 밴드 풀업 → 링 로우',
    timeTarget: '서브 8분 (엘리트), 12분 이하 (경쟁), 18분 이하 (일반)',
    tags: ['로잉', '쓰러스터', '풀업', '카디오'],
  },
  {
    id: 'lynne',
    name: 'Lynne',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '5라운드, 각 동작 최대 반복 (시간 제한 없음)\n\n벤치 프레스 (체중)\n풀업 (최대)',
    movements: ['벤치 프레스', '풀업'],
    scaling: '• 벤치 프레스: 체중 → 체중의 75% → 체중의 50%\n• 풀업: 밴드 풀업 → 링 로우\n• 스코어: 총 반복수 합계',
    timeTarget: '스코어 기반 - 총 반복수 150+ (엘리트)',
    rounds: 5,
    tags: ['근력', '벤치프레스', '풀업', '맥스리프트'],
  },
  {
    id: 'nicole',
    name: 'Nicole',
    type: 'girl',
    equipment: ['barbell', 'bodyweight'],
    description: '20분 AMRAP\n\n400m 런\n최대 풀업\n\n(매 라운드마다 이전 풀업 개수를 넘지 않으면 다음 라운드 시작)',
    movements: ['400m 런', '풀업'],
    scaling: '• 풀업: 밴드 풀업 → 링 로우\n• 런: 조깅 페이스 유지\n• 스코어: 총 풀업 개수',
    timeTarget: '20분 AMRAP - 풀업 총 100개+ (엘리트)',
    tags: ['AMRAP', '런닝', '풀업', '지구력'],
  },

  // ===== HERO WODs =====
  {
    id: 'murph',
    name: 'Murph',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 해군 중위 마이클 머피를 추모하는 WOD.\n\n1마일 런\n100 풀업\n200 푸시업\n300 스쿼트\n1마일 런\n\n*파티션 허용 (예: 20라운드 × 5풀업+10푸시업+15스쿼트)\n**20파운드 조끼/배낭 착용 권장',
    movements: ['1마일 런', '풀업', '푸시업', '에어 스쿼트'],
    scaling: '• 풀업: 밴드 풀업 → 링 로우\n• 조끼 없이 맨몸으로 시작\n• 파티션: 20라운드 치퍼 형식 추천\n• 런: 800m로 줄이기 가능',
    timeTarget: '서브 40분 (엘리트), 55분 이하 (경쟁), 70분 이하 (일반)',
    tags: ['히어로', '메모리얼', '지구력', '맨몸', '조끼'],
  },
  {
    id: 'dt',
    name: 'DT',
    type: 'hero',
    equipment: ['barbell'],
    description: '미 공군 상병 티모시 데이비스를 추모하는 WOD.\n\n5라운드 for time:\n12 데드리프트 (70kg/47.5kg)\n9 행 파워 클린\n6 푸시 저크',
    movements: ['데드리프트', '행 파워 클린', '푸시 저크'],
    scaling: '• 권장 무게: 70kg → 50kg → 35kg\n• 바벨을 내려놓지 않고 연결 동작 권장\n• 무게 조정 시 세 동작 모두 동일 무게',
    timeTarget: '서브 7분 (엘리트), 10분 이하 (경쟁), 15분 이하 (일반)',
    rounds: 5,
    tags: ['히어로', '바벨', '5라운드', '파워'],
  },
  {
    id: 'michael',
    name: 'Michael',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 해군 소위 마이클 맥게버른을 추모하는 WOD.\n\n3라운드 for time:\n800m 런\n50 백 익스텐션\n50 싯업',
    movements: ['800m 런', '백 익스텐션', '싯업'],
    scaling: '• 백 익스텐션: GHD 백 익스텐션 또는 슈퍼맨\n• 런: 로잉 800m 대체 가능\n• 싯업: 앵커드 싯업 가능',
    timeTarget: '서브 20분 (엘리트), 28분 이하 (경쟁)',
    rounds: 3,
    tags: ['히어로', '런닝', '코어', '3라운드'],
  },
  {
    id: 'jt',
    name: 'JT',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 해군 특수부대원 제프 테일러를 추모하는 WOD.\n\n21-15-9 for time:\n핸드스탠드 푸시업\n링딥\n푸시업',
    movements: ['핸드스탠드 푸시업', '링딥', '푸시업'],
    scaling: '• HSPU: 파이크 푸시업 → 박스 파이크\n• 링딥: 밴드 링딥 → 박스딥\n• 상체 근력 WOD',
    timeTarget: '서브 8분 (엘리트), 15분 이하 (경쟁)',
    tags: ['히어로', '21-15-9', '상체', '맨몸'],
  },
  {
    id: 'randy',
    name: 'Randy',
    type: 'hero',
    equipment: ['barbell'],
    description: '미 공군 특수요원 랜디 하드을 추모하는 WOD.\n\n75 파워 스내치 (35kg) for time',
    movements: ['파워 스내치'],
    scaling: '• 권장 무게: 35kg → 25kg → 15kg\n• 분할: 5×15 또는 10×7~8\n• 기술 WOD: 스내치 동작 완벽히 숙지 후 도전',
    timeTarget: '서브 6분 (엘리트), 10분 이하 (경쟁), 15분 이하 (일반)',
    tags: ['히어로', '스내치', '바벨', '반복'],
  },
  {
    id: 'ryan',
    name: 'Ryan',
    type: 'hero',
    equipment: ['box', 'barbell'],
    description: '미 육군 레인저 라이언 잡을 추모하는 WOD.\n\n5라운드 for time:\n7 머슬업\n21 버피 박스 점프 (61cm)',
    movements: ['링 머슬업', '버피 박스 점프'],
    scaling: '• 머슬업: 체스트 투 바 풀업 → 밴드 머슬업\n• 버피 박스: 버피 + 스텝 업으로 대체\n• 고강도 WOD',
    timeTarget: '서브 20분 (엘리트), 30분 이하 (경쟁)',
    rounds: 5,
    tags: ['히어로', '머슬업', '버피', '5라운드'],
  },
  {
    id: 'holleyman',
    name: 'Holleyman',
    type: 'hero',
    equipment: ['barbell', 'bodyweight', 'box'],
    description: '미 육군 특전사 아론 홀레이만을 추모하는 WOD.\n\n30라운드 for time:\n5 파워 클린 (70kg)\n3 핸드스탠드 푸시업\n1 머슬업',
    movements: ['파워 클린', '핸드스탠드 푸시업', '링 머슬업'],
    scaling: '• 파워 클린: 70kg → 50kg → 35kg\n• HSPU: 파이크 푸시업\n• 머슬업: 체스트 투 바 풀업 2개\n• 30라운드 완주 목표',
    timeTarget: '40분 이하 (엘리트), 55분 이하 (경쟁)',
    rounds: 30,
    tags: ['히어로', '30라운드', '고급', '치퍼'],
  },
  {
    id: 'kalsu',
    name: 'Kalsu',
    type: 'hero',
    equipment: ['barbell'],
    description: '미 NFL 선수 밥 칼수를 추모하는 WOD.\n\n100 쓰러스터 (60kg/43kg) for time\n매 분 시작 시: 5 버피 수행\n(타이머 시작 시 5 버피로 시작)',
    movements: ['쓰러스터', '버피'],
    scaling: '• 권장 무게: 60kg → 43kg → 30kg\n• 버피 먼저 수행 후 남은 시간 쓰러스터\n• 가장 힘든 WOD 중 하나',
    timeTarget: '20분 이하 (엘리트), 30분 이하 (경쟁)',
    tags: ['히어로', '쓰러스터', '버피', 'EMOM혼합'],
  },
  {
    id: 'jason',
    name: 'Jason',
    type: 'hero',
    equipment: ['bodyweight'],
    description: '미 육군 스태프 상사 제이슨 고든을 추모하는 WOD.\n\n100 스쿼트\n5 머슬업\n75 스쿼트\n10 머슬업\n50 스쿼트\n15 머슬업\n25 스쿼트\n20 머슬업',
    movements: ['에어 스쿼트', '링 머슬업'],
    scaling: '• 머슬업: 체스트 투 바 풀업 2:1\n• 스쿼트: 낮은 고관절 깊이 유지\n• 치퍼 형식',
    timeTarget: '20분 이하 (엘리트), 30분 이하 (경쟁)',
    tags: ['히어로', '치퍼', '머슬업', '스쿼트'],
  },
  {
    id: 'danny',
    name: 'Danny',
    type: 'hero',
    equipment: ['box', 'barbell', 'bodyweight'],
    description: '미 육군 병사 대니 디에즈를 추모하는 WOD.\n\n20분 AMRAP:\n30 박스 점프 (61cm)\n20 푸시 프레스 (52.5kg)\n30 풀업',
    movements: ['박스 점프', '푸시 프레스', '풀업'],
    scaling: '• 박스: 61cm → 51cm → 41cm\n• 푸시 프레스: 52.5kg → 35kg → 22.5kg\n• 풀업: 밴드 풀업 → 링 로우',
    timeTarget: '20분 AMRAP - 5라운드+ (엘리트), 3라운드+ (경쟁)',
    tags: ['히어로', 'AMRAP', '20분', '박스점프'],
  },

  // ===== CrossFit Open WODs =====
  {
    id: 'open-11-1',
    name: '11.1',
    type: 'open',
    equipment: ['rope', 'bodyweight'],
    description: '10분 AMRAP:\n30 더블언더\n15 파워 스내치 (35kg/25kg)',
    movements: ['더블언더', '파워 스내치'],
    scaling: '• 더블언더: 2:1 싱글언더\n• 스내치: 35kg → 25kg → 15kg',
    timeTarget: '10분 AMRAP - 10라운드+ (엘리트)',
    tags: ['오픈', '2011', 'AMRAP', '더블언더'],
  },
  {
    id: 'open-12-1',
    name: '12.1',
    type: 'open',
    equipment: ['bodyweight'],
    description: '7분 AMRAP:\n버피',
    movements: ['버피'],
    scaling: '• 기준 동작 엄격하게 적용\n• 점프 후 양손 박수 확인\n• 100개+ 목표 (엘리트)',
    timeTarget: '7분 AMRAP - 100개+ (엘리트), 75개+ (경쟁)',
    tags: ['오픈', '2012', 'AMRAP', '버피'],
  },
  {
    id: 'open-13-1',
    name: '13.1',
    type: 'open',
    equipment: ['barbell', 'rope'],
    description: '17분 AMRAP:\n40 버피 박스 점프 (50cm)\n30 스내치 (35kg/25kg)\n30 버피 박스 점프\n30 스내치 (60kg/42.5kg)\n20 버피 박스 점프\n30 스내치 (102.5kg/70kg)\n10 버피 박스 점프\n최대 스내치 (145kg/102.5kg)',
    movements: ['버피 박스 점프', '스내치'],
    scaling: '• 각 무게 단계별 스케일링\n• 시간 내 최대한 진행',
    timeTarget: '17분 AMRAP',
    tags: ['오픈', '2013', '스내치', '치퍼'],
  },
  {
    id: 'open-14-1',
    name: '14.1',
    type: 'open',
    equipment: ['rope', 'barbell'],
    description: '10분 AMRAP:\n30 더블언더\n15 파워 스내치 (35kg/25kg)',
    movements: ['더블언더', '파워 스내치'],
    scaling: '• 더블언더: 2:1 싱글언더\n• 스내치: 35kg → 25kg',
    timeTarget: '10분 AMRAP',
    tags: ['오픈', '2014', 'AMRAP', '더블언더'],
  },
  {
    id: 'open-15-1',
    name: '15.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '9분 AMRAP:\n15 토스토바\n10 데드리프트 (70kg/47.5kg)\n5 스냇치 (70kg/47.5kg)\n\n이후 6분 내 1RM 클린 앤 저크',
    movements: ['토스투바', '데드리프트', '스내치', '클린 앤 저크'],
    scaling: '• 무게 스케일링 가능\n• 클린 앤 저크 1RM 기록',
    timeTarget: '9분 AMRAP + 6분 1RM',
    tags: ['오픈', '2015', 'AMRAP', '1RM'],
  },
  {
    id: 'open-16-1',
    name: '16.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '20분 AMRAP:\n25피트 오버헤드 워킹 런지 (43kg/30kg)\n8 버피 박스 점프 (50cm)\n25피트 오버헤드 워킹 런지\n8 체스트 투 바 풀업',
    movements: ['오버헤드 워킹 런지', '버피 박스 점프', '체스트 투 바 풀업'],
    scaling: '• 런지 무게: 43kg → 20kg\n• 체스트 투 바: 점핑 풀업 → 링 로우',
    timeTarget: '20분 AMRAP',
    tags: ['오픈', '2016', 'AMRAP', '런지'],
  },
  {
    id: 'open-17-1',
    name: '17.1',
    type: 'open',
    equipment: ['dumbbell', 'bodyweight'],
    description: '20분 AMRAP:\n10 덤벨 스내치 (22.5kg/15kg)\n15 박스 점프 오버 (50cm)',
    movements: ['덤벨 스내치', '박스 점프 오버'],
    scaling: '• 덤벨: 22.5kg → 15kg → 10kg\n• 박스: 50cm → 41cm → 24cm\n• 덤벨 오픈의 시작',
    timeTarget: '20분 AMRAP',
    tags: ['오픈', '2017', 'AMRAP', '덤벨'],
  },
  {
    id: 'open-18-1',
    name: '18.1',
    type: 'open',
    equipment: ['dumbbell', 'bodyweight'],
    description: '20분 AMRAP:\n8 토스투바\n10 핸드릴리즈 푸시업\n12 덤벨 스내치 (22.5kg/15kg)',
    movements: ['토스투바', '핸드릴리즈 푸시업', '덤벨 스내치'],
    scaling: '• 덤벨: 22.5kg → 15kg → 10kg\n• 토스투바: 니즈투체스트 → 싯업',
    timeTarget: '20분 AMRAP',
    tags: ['오픈', '2018', 'AMRAP', '덤벨'],
  },
  {
    id: 'open-19-1',
    name: '19.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '15분 AMRAP:\n19 월볼 (9kg/6kg)\n19 칼슈나이더 (50cm)',
    movements: ['월볼', '칼슈나이더'],
    scaling: '• 월볼: 9kg → 6kg → 4kg\n• 칼슈나이더: 버피 + 박스 점프 오버\n• 박스: 50cm → 41cm',
    timeTarget: '15분 AMRAP',
    tags: ['오픈', '2019', 'AMRAP', '월볼'],
  },
  {
    id: 'open-20-1',
    name: '20.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '10라운드 for time (8분 제한):\n8 그라운드 투 오버헤드 (43kg/29kg)\n10 바 페이싱 버피',
    movements: ['그라운드 투 오버헤드', '바 페이싱 버피'],
    scaling: '• 무게: 43kg → 29kg → 20kg\n• 버피: 스텝 업/다운 가능',
    timeTarget: '8분 이내 10라운드',
    tags: ['오픈', '2020', '버피', 'GTO'],
  },
  {
    id: 'open-21-1',
    name: '21.1',
    type: 'open',
    equipment: ['rope', 'barbell'],
    description: '15분 AMRAP:\n21 더블언더\n15 파워 스내치 (25kg)\n9 바 머슬업',
    movements: ['더블언더', '파워 스내치', '바 머슬업'],
    scaling: '• 더블언더: 2:1 싱글언더\n• 스내치: 25kg → 15kg\n• 머슬업: 체스트 투 바 풀업',
    timeTarget: '15분 AMRAP',
    tags: ['오픈', '2021', 'AMRAP', '더블언더'],
  },
  {
    id: 'open-22-1',
    name: '22.1',
    type: 'open',
    equipment: ['barbell', 'bodyweight'],
    description: '15분 AMRAP:\n3 월 워크 (4.5m)\n3 링 머슬업\n3 파워 스내치 (43kg)',
    movements: ['월 워크', '링 머슬업', '파워 스내치'],
    scaling: '• 월 워크: 인치웜 → 파이크 푸시업\n• 머슬업: 체스트 투 바 풀업\n• 스내치: 43kg → 29kg → 20kg',
    timeTarget: '15분 AMRAP',
    tags: ['오픈', '2022', 'AMRAP', '고급'],
  },
  {
    id: 'open-23-1',
    name: '23.1',
    type: 'open',
    equipment: ['barbell', 'rope', 'bodyweight'],
    description: '14분 AMRAP:\n60 칼로리 로잉\n50 쓰러스터 (20kg)\n40 싱글 언더\n30 싯업\n20 파워 클린 앤 저크 (43kg)\n10 더블 언더',
    movements: ['로잉', '쓰러스터', '싱글언더', '싯업', '파워 클린 앤 저크', '더블언더'],
    scaling: '• 각 무게 스케일링 가능\n• 로잉: 바이크 에르고 대체 가능\n• 시간 내 최대한 진행',
    timeTarget: '14분 AMRAP',
    tags: ['오픈', '2023', 'AMRAP', '치퍼'],
  },
]

export const WOD_CATEGORIES = [
  { id: 'all', label: '전체' },
  { id: 'girl', label: 'Girl WODs' },
  { id: 'hero', label: 'Hero WODs' },
  { id: 'open', label: 'CrossFit Open' },
  { id: 'benchmark', label: '벤치마크' },
]

export const EQUIPMENT_FILTERS = [
  { id: 'all', label: '전체' },
  { id: 'barbell', label: '바벨' },
  { id: 'dumbbell', label: '덤벨' },
  { id: 'bodyweight', label: '맨몸' },
  { id: 'kettlebell', label: '케틀벨' },
  { id: 'rope', label: '줄넘기' },
  { id: 'box', label: '박스' },
]
